name: Create version tag

on:
  pull_request:
    branches: [ "main" ]
    # pull_request_target:
    # types:
      # - closed

jobs:
  create_version_tag:
    # if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install package
      run: |
        pip install -e .
    - name: Extract version
      run: |
        VERSION=$(python3 -c \
          "from importlib.metadata import version; \
          print(version('strunc'))")
        echo $VERSION
    - name: Create tag
      run: |
        /usr/bin/git status
        git remote -v
        /usr/bin/git config user.name "${GITHUB_ACTOR}"
        /usr/bin/git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        echo first
        git tag
        git tag $VERSION
        git tag test
        echo second
        git tag
        /usr/bin/git push origin $VERSION
